"""update_subscription_plans_schema

Revision ID: 0585e96f8e45
Revises: ba25a9feca25
Create Date: 2025-07-27 15:09:18.025792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0585e96f8e45'
down_revision = 'ba25a9feca25'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_plans', sa.Column('months', sa.Integer(), nullable=False))
    op.add_column('subscription_plans', sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('subscription_plans', sa.Column('discounted_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('subscription_plans', sa.Column('is_custom', sa.Boolean(), nullable=True))
    op.drop_column('subscription_plans', 'duration_months')
    op.drop_column('subscription_plans', 'features')
    op.drop_column('subscription_plans', 'original_price')
    op.drop_column('subscription_plans', 'description')
    op.drop_column('subscription_plans', 'name')
    op.drop_column('subscription_plans', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_plans', sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('subscription_plans', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('subscription_plans', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('subscription_plans', sa.Column('original_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('subscription_plans', sa.Column('features', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('subscription_plans', sa.Column('duration_months', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('subscription_plans', 'is_custom')
    op.drop_column('subscription_plans', 'discounted_amount')
    op.drop_column('subscription_plans', 'amount')
    op.drop_column('subscription_plans', 'months')
    # ### end Alembic commands ###
