"""add_missing_student_columns

Revision ID: 12089a17ee7e
Revises: 42cf3b48a914
Create Date: 2025-09-21 03:51:33.721967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12089a17ee7e'
down_revision = '42cf3b48a914'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
