"""Add student removal system and missing fields

Revision ID: 1ee31fc54504
Revises: f4118aa7b83e
Create Date: 2025-09-22 00:47:35.420464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1ee31fc54504'
down_revision = 'f4118aa7b83e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the removal request status enum
    removal_request_status = postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='removalrequeststatus')
    removal_request_status.create(op.get_bind())
    
    # Create the student_removal_requests table
    op.create_table('student_removal_requests',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('student_id', sa.UUID(), nullable=False),
        sa.Column('admin_id', sa.UUID(), nullable=False),
        sa.Column('reason', sa.TEXT(), nullable=False),
        sa.Column('status', removal_request_status, nullable=False),
        sa.Column('subscription_end_date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('days_overdue', sa.VARCHAR(length=50), nullable=False),
        sa.Column('admin_notes', sa.TEXT(), nullable=True),
        sa.Column('processed_by', sa.UUID(), nullable=True),
        sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], ),
        sa.ForeignKeyConstraint(['processed_by'], ['admin_users.id'], ),
        sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.add_column('admin_users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('students', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('students', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('students', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('students', sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'removed_at')
    op.drop_column('students', 'is_active')
    op.drop_column('students', 'last_name')
    op.drop_column('students', 'first_name')
    op.drop_column('admin_users', 'name')
    op.drop_table('student_removal_requests')
    # Drop the enum
    removal_request_status = postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='removalrequeststatus')
    removal_request_status.drop(op.get_bind())
    # ### end Alembic commands ###
