"""add_payment_fields_to_bookings

Revision ID: 32465a9065a8
Revises: 9da141b0fd47
Create Date: 2025-09-20 01:36:13.974238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32465a9065a8'
down_revision = '9da141b0fd47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add payment fields to seat_bookings table
    op.add_column('seat_bookings', sa.Column('payment_status', sa.String(), nullable=True))
    op.add_column('seat_bookings', sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('seat_bookings', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('seat_bookings', sa.Column('payment_reference', sa.String(), nullable=True))
    
    # Add other missing fields
    op.add_column('seat_bookings', sa.Column('seat_id', sa.String(), nullable=True))
    op.add_column('seat_bookings', sa.Column('subscription_plan_id', sa.UUID(), nullable=True))
    op.add_column('seat_bookings', sa.Column('date', sa.String(), nullable=True))
    op.add_column('seat_bookings', sa.Column('start_time', sa.String(), nullable=True))
    op.add_column('seat_bookings', sa.Column('end_time', sa.String(), nullable=True))
    op.add_column('seat_bookings', sa.Column('purpose', sa.Text(), nullable=True))
    
    # Add foreign key constraint for subscription_plan_id
    op.create_foreign_key('fk_seat_bookings_subscription_plan_id', 'seat_bookings', 'subscription_plans', ['subscription_plan_id'], ['id'])
    
    # Set default values for existing records
    op.execute("UPDATE seat_bookings SET payment_status = 'pending' WHERE payment_status IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove foreign key constraint
    op.drop_constraint('fk_seat_bookings_subscription_plan_id', 'seat_bookings', type_='foreignkey')
    
    # Remove added columns
    op.drop_column('seat_bookings', 'purpose')
    op.drop_column('seat_bookings', 'end_time')
    op.drop_column('seat_bookings', 'start_time')
    op.drop_column('seat_bookings', 'date')
    op.drop_column('seat_bookings', 'subscription_plan_id')
    op.drop_column('seat_bookings', 'seat_id')
    op.drop_column('seat_bookings', 'payment_reference')
    op.drop_column('seat_bookings', 'payment_method')
    op.drop_column('seat_bookings', 'payment_date')
    op.drop_column('seat_bookings', 'payment_status')
    # ### end Alembic commands ###
