"""add_profile_image_to_students

Revision ID: 42cf3b48a914
Revises: 32465a9065a8
Create Date: 2025-09-21 03:51:13.981533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42cf3b48a914'
down_revision = '32465a9065a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('profile_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'profile_image')
    # ### end Alembic commands ###
