"""add_student_booking_fields

Revision ID: 9da141b0fd47
Revises: f10bbc798173
Create Date: 2025-09-20 00:54:49.954045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9da141b0fd47'
down_revision = 'f10bbc798173'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Update null values in referral_codes.user_type
    op.execute("UPDATE referral_codes SET user_type = 'admin' WHERE user_type IS NULL")
    op.alter_column('referral_codes', 'user_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('referral_codes_user_id_fkey', 'referral_codes', type_='foreignkey')
    
    # Update null values in referrals.referrer_type
    op.execute("UPDATE referrals SET referrer_type = 'admin' WHERE referrer_type IS NULL")
    op.alter_column('referrals', 'referrer_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('referrals_referred_id_fkey', 'referrals', type_='foreignkey')
    op.drop_constraint('referrals_referrer_id_fkey', 'referrals', type_='foreignkey')
    op.add_column('seat_bookings', sa.Column('seat_id', sa.String(), nullable=True))
    op.add_column('seat_bookings', sa.Column('subscription_plan_id', sa.UUID(), nullable=True))
    op.add_column('seat_bookings', sa.Column('date', sa.String(), nullable=True))
    op.add_column('seat_bookings', sa.Column('start_time', sa.String(), nullable=True))
    op.add_column('seat_bookings', sa.Column('end_time', sa.String(), nullable=True))
    op.add_column('seat_bookings', sa.Column('purpose', sa.Text(), nullable=True))
    op.alter_column('seat_bookings', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('seat_bookings', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('seat_bookings', 'mobile',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('seat_bookings', 'address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('seat_bookings', 'subscription_months',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('seat_bookings', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.create_foreign_key(None, 'seat_bookings', 'subscription_plans', ['subscription_plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seat_bookings', type_='foreignkey')
    op.alter_column('seat_bookings', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('seat_bookings', 'subscription_months',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('seat_bookings', 'address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('seat_bookings', 'mobile',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('seat_bookings', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('seat_bookings', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('seat_bookings', 'purpose')
    op.drop_column('seat_bookings', 'end_time')
    op.drop_column('seat_bookings', 'start_time')
    op.drop_column('seat_bookings', 'date')
    op.drop_column('seat_bookings', 'subscription_plan_id')
    op.drop_column('seat_bookings', 'seat_id')
    op.create_foreign_key('referrals_referrer_id_fkey', 'referrals', 'admin_users', ['referrer_id'], ['user_id'])
    op.create_foreign_key('referrals_referred_id_fkey', 'referrals', 'admin_users', ['referred_id'], ['user_id'])
    op.alter_column('referrals', 'referrer_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key('referral_codes_user_id_fkey', 'referral_codes', 'admin_users', ['user_id'], ['user_id'])
    op.alter_column('referral_codes', 'user_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
