"""add library_id to subscription_plans

Revision ID: ba25a9feca25
Revises: 26ef3d78a8e9
Create Date: 2025-07-16 16:18:21.375120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba25a9feca25'
down_revision = '26ef3d78a8e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_plans', sa.Column('library_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'subscription_plans', 'admin_details', ['library_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscription_plans', type_='foreignkey')
    op.drop_column('subscription_plans', 'library_id')
    # ### end Alembic commands ###
