"""fix_hashed_password_nullable

Revision ID: d8fc480b7c0b
Revises: 12089a17ee7e
Create Date: 2025-09-21 03:52:03.861626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8fc480b7c0b'
down_revision = '12089a17ee7e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
